[versions]
agp = "8.9.2"
kotlin = "2.1.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2025.04.01"
# Compose
compose = "1.8.0"
navigation = "2.8.9"
compose_hilt_navigation = "1.2.0"
compose-constraint = "1.1.1"
paging-compose = "3.3.6"
coroutine = "1.10.2"
datastore = "1.1.5"
material3 = "1.3.2"
hilt = "2.56.2"
ksp = "2.1.20-2.0.0"
coil-compose = "2.2.2"
gson = "2.10.1"
retrofit = "2.9.0"
okhttp = "4.12.0"
okhttp-logging-interceptor = "4.10.0"
work-manager = "2.10.1"
appcompat = "1.7.0"
material = "1.12.0"


[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3"}
material3_windowsize = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3"}
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }

composeRuntime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
composeConstraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraint" }
composeNavigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
composeAnimation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
composeFoundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
composeHiltNavigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "compose_hilt_navigation" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }

coroutineCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
coroutineAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
datastore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
datastoreProto = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }

# retrofit/ network
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitGsonConverter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpLoggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-logging-interceptor" }

# work manager
workRuntime = { module = "androidx.work:work-runtime", version.ref = "work-manager" }
workKotlinWithCoroutines = { module = "androidx.work:work-runtime-ktx", version.ref = "work-manager" }

# hilt
hilt-android = {module = "com.google.dagger:hilt-android", version.ref = "hilt"}
hilt-compiler = {module = "com.google.dagger:hilt-compiler", version.ref = "hilt"}
[bundles]
core = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "androidx-lifecycle-runtime-ktx"
]

compose = [
    "androidx-ui",
    "androidx-activity-compose",
    "androidx-ui-graphics",
    "androidx-ui-tooling",
    "androidx-ui-tooling-preview",
    "androidx-ui-test-manifest",
    "androidx-material3",
    "material3",
    "material3_windowsize",
    "composeRuntime",
    "composeConstraintLayout",
    "composeNavigation",
    "composeAnimation",
    "composeFoundation",
    "composeHiltNavigation",
    "paging-compose"
]
coroutines = [
    "coroutineCore",
    "coroutineAndroid",
    "datastore",
    "datastoreProto",
    "workRuntime",
    "workKotlinWithCoroutines"
]

network = [
    "gson",
    "retrofit",
    "retrofitGsonConverter",
    "okhttp",
    "okhttpLoggingInterceptor"
]
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}

